
image:
  file: .gitpod.Dockerfile

tasks:
  - init: cargo install wasm-pack 
      && cd myproject
      && wasm-pack build
      && npm init wasm-app www
      && cd www
      && sed -i -e 's/hello-wasm-pack/myproject/g' index.js
      && npm install
      && cd ../pkg/
      && npm link
      && cd ../www/
      && npm link myproject

    command: export TZ="Asia/Tokyo"

vscode:
  extensions:
    - rust-lang.rust
    - vscodevim.vim
